logs:
  - name: root
    level: info
    formatter: '%d%T%m%n'
    appenders:
      - type: FileLogAppender
        file: /root/sylar-project/sylar/root.txt
      - type: StdoutLogAppender
  - name: system
    level: debug
    formatter: '%d%T%m%n'
    appenders:
    - type: FileLogAppender
      file: /root/sylar-project/sylar/system.txt
      formatter: '%d%T[%p]%T%m%n'
    - type: StdoutLogAppender

